[tool.poetry]
name = "sng-demo"
version = "0.1.0"
description = ""
authors = ["Ivan Despot <ivan.despot@memgraph.io>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1.2"
pymgclient = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
